### ISSUE TITLE
дублювання коду

### ISSUE THREAD

**Issue by pecourses** [vXIXk/Assignments-repo#2]
https://github.com/vXIXk/Assignments-repo/blob/2d3ce26ec97c3e179d91a4607481cbac6e165a69/assets/css/styles.css#L56-L69
- коли у кількох елементів стилі частково дублюються, зручно поступати отак, щоб отримати єдине джерело істини:
```css
.info_block1,
.info_block2 {
  padding: 2.3% 26% 2%;
  color: white;
}
.info_block1 {
  background-color: #3498db;
}
.info_block2 {
  background-color: #3a3b3c;
}
``` 
Тоді, якщо, наприклад, доведеться міняти колір шрифта, треба буде внести одну зміну в одному рядку, а не в двох, як в початковому варіанті.
