### ISSUE TITLE
імейл

### ISSUE THREAD

**Issue by pecourses** [vXIXk/Assignments-repo#3]
https://github.com/vXIXk/Assignments-repo/blob/43edd498afc25f30771b7c592ed7f32e56afbfc9/index.html#L107
- для UX краще буде посилання з mailto

https://github.com/vXIXk/Assignments-repo/blob/43edd498afc25f30771b7c592ed7f32e56afbfc9/assets/css/styles.css#L153-L156
- бічні великі падінгі інколи підступні)
![image](https://github.com/vXIXk/Assignments-repo/assets/67504221/3a6bc594-ceae-429b-9f0a-000b4217e2c6)
Центрувати надійніше через text-align, а невеличкий гарантований відступ є і у батьківського. Але все одно лишиться проблема з тим, що йому не вистачає ширини при звуженні. Можна обрізати крапочками і додати title:
![image](https://github.com/vXIXk/Assignments-repo/assets/67504221/aa6685a1-e938-445c-a159-759eb3b32fa2)
(скрін не лове вказівник мишки, тому його не видно, він насправді на імейлі)
```css
span {
  display: block;
  padding: 2em 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
